
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hms?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password-1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include:
        - info
        - health
        - refresh
        
server:
  port: 0
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
        
info:
  app:
    name: patient service
    description: This service handles all patient information
    version: 1.0
    java:
      version: 1.9
    spring:
      cloud:
        version: Hoxton.SR6